sudo: required
language: clojure
lein: 2.6.1
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
services:
  - docker
before_install:
  - mkdir system1 && mkdir system2
  - "curl -sSL -H 'Accept: application/vnd.github.v3.raw' https://api.github.com/repos/tiagofvalerio/system1/tarball/master | tar zx --strip-components 1 -C system1"
  - "curl -sSL -H 'Accept: application/vnd.github.v3.raw' https://api.github.com/repos/tiagofvalerio/system2/tarball/master | tar zx --strip-components 1 -C system2"

script:
  - docker-compose up -d
  - lein test
