sudo: required
language: clojure
lein: 2.6.1
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir system1 && mkdir system2
  - "curl -sSL -H 'Accept: application/vnd.github.v3.raw' https://api.github.com/repos/tiagofvalerio/system1/tarball/master | tar zx --strip-components 1 -C system1"
  - "curl -sSL -H 'Accept: application/vnd.github.v3.raw' https://api.github.com/repos/tiagofvalerio/system2/tarball/master | tar zx --strip-components 1 -C system2"
  - cd system1 && lein uberjar && cd ../
  - cd system2 && lein uberjar && cd ../

script:
  - docker-compose up -d
  #- docker logs postgres
  - sleep 20
  #- docker logs postgres
  #- docker ps -a
  #- netstat -tulpn
  - lein test
  #- echo "system2**************************"
  #- docker logs system12test_system2_1
  #- docker logs system12test_system2_1
  #- docker logs system12test_system1_1
  #- docker logs system12test_system1_1
