version: '3'
services:
  system1:
    build: ./system1
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
     - "8080:8080"
  system2:
    build: ./system2
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - "8081:8080"
  postgres:
    build: .
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
