version: '3'
services:
  system1:
    build: ./system1
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres:postgres
      - rabbitmq:rabbitmq
    ports:
      - "8080:8080"
    environment:
      - KRAKEN_BROKER_URL=amqp://rabbitmq
  system2:
    build: ./system2
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres:postgres
      - rabbitmq:rabbitmq
    ports:
      - "8081:8080"
    environment:
      - KRAKEN_BROKER_URL=amqp://rabbitmq
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - "RABBITMQ_NODENAME=rabbitmq"
  postgres:
    build: .
    restart: always
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
